#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

#
# Alias
#
alias battery-statu='upower -i /org/freedesktop/UPower/devices/battery_BAT0| grep -E "state|to\ full|percentage"'
alias vi="nvim"
alias vim="nvim"
alias py.test='py.test -s --tb=native'
alias use_anaconda="export PATH=\"~/anaconda3/bin:$PATH\""
alias docker-remove-all-containers="docker ps -aq | xargs docker stop && docker ps -aq | xargs docker rm"
alias qbittorrent="QT_AUTO_SCREEN_SCALE_FACTOR=0 qbittorrent"
